name       : qogir-icon-theme
version    : '20230605'
release    : 1
source     :
    - https://github.com/vinceliuice/Qogir-icon-theme/archive/refs/tags/2023-06-05.tar.gz : 618768d3592238f0d11379b4a0261434c332bb63c30d3ea85ea26f80bf199043
license    : GPL-3.0
component  : desktop.theme
summary    : A colorful design icon and cursor theme for linux desktops
description: |
    A flat colorful design icon theme for linux desktops
builddeps  :
    - libgtk-3
install    : |
    mkdir -p $installdir/usr/share/icons
    ./install.sh -t default -d $installdir/usr/share/icons

    # Remove cache and non-useful files
    rm $installdir/usr/share/icons/*/{icon-theme.cache,AUTHORS,COPYING}
